name: clemens
favicon: null
layout_spectrum: 0.2356937164440751
typography_spectrum: 0.8465711632743478
title: 'This is me!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.21305394358932972
  lightness: 0.17468020203523338
  saturation: 0.7560572030488402
  rhythmicContrast: 0.21294170385226607
purpose: []
